services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 5173:80
    build:
      context: .
      dockerfile: Dockerfile.vue
    volumes:
      - ./conf.d/prod.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
  caddy:
    container_name: caddy
    restart: always
    image: caddy:2.0.0-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - backend
  db:
    container_name: calloux-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    networks:
      - backend
  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile-prod.django
    command: gunicorn Web_rest_api.wsgi:application --bind 0.0.0.0:8888
    depends_on:
      - db
    ports:
      - 8888:8888
    networks:
      - backend

networks:
  backend:
